use super::Error;
#[derive(Clone, Copy)]
pub(super) enum Field {
    Id,
    Digest,
    U32,
    U64,
    Bool,
    Text,
    Bytes,
    OptionalU64,
    IdMap,
    Set,
    Record(u16, u16),
    Records(u16, u16, Option<usize>),
    Outcome,
}
pub(super) fn fields(domain: u16, kind: u16) -> Result<&'static [Field], Error> {
    use Field::*;
    let schema: &[Field] = match (domain, kind) {
        (1, 1) => &[Id, Id, Id, Id, Id, U32, Digest],
        (1, 2) => &[Record(1, 1), IdMap, Record(6, 1), OptionalU64, Record(6, 2)],
        (2, 1) => &[
            Id,
            Id,
            U64,
            U64,
            Digest,
            IdMap,
            Records(6, 5, Some(0)),
            Records(6, 4, Some(0)),
            Records(6, 6, Some(0)),
            Records(6, 7, Some(0)),
            Records(6, 8, Some(1)),
            Records(6, 9, Some(0)),
            Record(6, 2),
        ],
        (3, 1) => &[
            Id,
            Id,
            U32,
            Digest,
            Digest,
            U64,
            IdMap,
            IdMap,
            Records(6, 1, None),
            Records(6, 4, Some(0)),
            Record(6, 2),
        ],
        (4, 1) => &[
            Id,
            U64,
            Digest,
            U64,
            U64,
            Digest,
            Records(6, 8, Some(1)),
            Records(6, 1, None),
            Records(6, 4, Some(0)),
            Digest,
            Record(6, 2),
        ],
        (6, 1) => &[U32, Bytes],
        (6, 2) => &[Set, Set],
        (6, 3) => &[Id, U64],
        (6, 4) => &[Id, U32, Record(6, 1)],
        (6, 5) => &[Id, Record(6, 3), Record(6, 1)],
        (6, 6) => &[Id, U64, Record(6, 1)],
        (6, 7) => &[Id, Record(6, 1)],
        (6, 8) => &[Id, Id, Id, Digest, U32, Outcome, OptionalU64],
        (6, 9) => &[Id, Digest, Record(6, 8)],
        (6, 10) => &[U32, Text, Set, Set, Bool],
        _ => return Err(Error::InvalidProfile),
    };
    Ok(schema)
}
