package nf.nex.reference;

import java.util.ArrayList;
import java.util.List;
import static nf.nex.reference.PeaceTraversalReference.*;

/** Independent expected traces from the pinned source loop, not generated by the implementation. */
final class PeaceTraversalCharacterization {
    private PeaceTraversalCharacterization() {}
    private static Enemy enemy(String id, int bits, ReportedReturn returned) {
        return new Enemy(id, bits, false, true, false, false, returned);
    }
    private static Visit visit(String id, Step step) { return new Visit(id, step); }
    static int run() {
        // First runtime RED must be this assertion, with unchanged test bytes through GREEN.
        List<Enemy> first = List.of(enemy("high", 0x40400000, ReportedReturn.NULL),
                enemy("low", 0x3f800000, ReportedReturn.NULL),
                enemy("fourth", 0x40800000, ReportedReturn.NOT_SUPPLIED),
                enemy("middle", 0x40000000, ReportedReturn.NULL));
        Result ordered = evaluatePassedOuterGates(first);
        equal(ordered.orderedEnemies(), List.of("low", "middle", "high", "fourth"),
                "source comparator is ascending, not the descending comment");
        equal(ordered.visits(), List.of(visit("low", Step.NULL_RETURN), visit("middle", Step.NULL_RETURN),
                visit("high", Step.NULL_RETURN)), "exactly three null returns stop before fourth");
        equal(ordered.nullAttempts(), 3, "null attempt count");
        equal(ordered.cacheRefreshRequests(), List.of(), "no reported return means no refresh request");

        List<Enemy> skipped = List.of(
                new Enemy("recent", 0, true, false, true, true, ReportedReturn.NOT_SUPPLIED),
                new Enemy("cannot", 0x3f800000, false, false, true, true, ReportedReturn.NOT_SUPPLIED),
                new Enemy("commission", 0x40000000, false, true, true, true, ReportedReturn.NOT_SUPPLIED),
                new Enemy("offensive", 0x40400000, false, true, false, true, ReportedReturn.NOT_SUPPLIED),
                enemy("one", 0x40800000, ReportedReturn.NULL), enemy("two", 0x40a00000, ReportedReturn.NULL),
                enemy("three", 0x40c00000, ReportedReturn.NULL), enemy("unreached", 0x40e00000, ReportedReturn.NOT_SUPPLIED));
        Result skips = evaluatePassedOuterGates(skipped);
        equal(skips.visits(), List.of(visit("recent", Step.RECENT_WAR), visit("cannot", Step.CANNOT_CEASEFIRE),
                visit("commission", Step.COMMISSIONED_PLAYER), visit("offensive", Step.OFFENSIVE_BLOCKED),
                visit("one", Step.NULL_RETURN), visit("two", Step.NULL_RETURN), visit("three", Step.NULL_RETURN)),
                "guard precedence and skipped enemies do not consume tries");
        equal(skips.nullAttempts(), 3, "three actual null calls after skips");

        Result success = evaluatePassedOuterGates(List.of(enemy("null", 0, ReportedReturn.NULL),
                enemy("returned", 0x3f800000, ReportedReturn.NON_NULL),
                enemy("unreached", 0x40000000, ReportedReturn.NOT_SUPPLIED)));
        equal(success.visits(), List.of(visit("null", Step.NULL_RETURN), visit("returned", Step.NON_NULL_RETURN)),
                "stop immediately on supplied non-null result");
        equal(success.returnedEnemy(), "returned", "reported return identity");
        equal(success.nullAttempts(), 1, "success does not consume a null try");
        equal(success.cacheRefreshRequests(), List.of(new CacheRefreshRequest(0)), "source requests refresh with +0f");

        List<Enemy> special = List.of(
                new Enemy("nan-first", 0xffc00002, true, true, false, false, ReportedReturn.NOT_SUPPLIED),
                new Enemy("positive-zero", 0, true, true, false, false, ReportedReturn.NOT_SUPPLIED),
                new Enemy("positive-infinity", 0x7f800000, true, true, false, false, ReportedReturn.NOT_SUPPLIED),
                new Enemy("negative-zero", 0x80000000, true, true, false, false, ReportedReturn.NOT_SUPPLIED),
                new Enemy("negative-infinity", 0xff800000, true, true, false, false, ReportedReturn.NOT_SUPPLIED),
                new Enemy("finite", 0x3f800000, true, true, false, false, ReportedReturn.NOT_SUPPLIED),
                new Enemy("nan-second", 0x7fc00001, true, true, false, false, ReportedReturn.NOT_SUPPLIED));
        equal(evaluatePassedOuterGates(special).orderedEnemies(),
                List.of("negative-infinity", "negative-zero", "positive-zero", "finite", "positive-infinity", "nan-first", "nan-second"),
                "Float.compare total ordering and stable NaN ties; no invented nonfinite refusal");
        equal(special.get(0).rawWearinessBits(), 0xffc00002, "copied raw NaN bits are retained");
        Result tie = evaluatePassedOuterGates(List.of(
                new Enemy("zeta", 0x3f800000, true, true, false, false, ReportedReturn.NOT_SUPPLIED),
                new Enemy("alpha", 0x3f800000, true, true, false, false, ReportedReturn.NOT_SUPPLIED)));
        equal(tie.orderedEnemies(), List.of("zeta", "alpha"), "equal finite scores retain supplied list order");
        Result repeated = evaluatePassedOuterGates(List.of(enemy("repeat", 0, ReportedReturn.NULL),
                enemy("repeat", 0, ReportedReturn.NULL), enemy("returned", 0x3f800000, ReportedReturn.NON_NULL)));
        equal(repeated.visits(), List.of(visit("repeat", Step.NULL_RETURN), visit("repeat", Step.NULL_RETURN),
                visit("returned", Step.NON_NULL_RETURN)), "source list occurrences are not deduplicated");
        equal(evaluatePassedOuterGates(List.of()), new Result(List.of(), List.of(), 0, null, List.of()), "empty supplied list");

        expectUnavailable(() -> evaluatePassedOuterGates(List.of(enemy("missing", 0, ReportedReturn.NOT_SUPPLIED))));
        ArrayList<Enemy> mutable = new ArrayList<>(first);
        Result copied = evaluatePassedOuterGates(mutable);
        equal(mutable, first, "sort does not mutate caller list");
        mutable.clear();
        equal(copied.orderedEnemies(), List.of("low", "middle", "high", "fourth"), "result copies survive caller changes");
        try { copied.visits().clear(); throw new AssertionError("mutable result list"); }
        catch (UnsupportedOperationException expected) {}
        ArrayList<Enemy> maximum = new ArrayList<>();
        for (int i = 0; i < 256; i++) maximum.add(new Enemy("entry", 0, true, true, false, false, ReportedReturn.NOT_SUPPLIED));
        equal(evaluatePassedOuterGates(maximum).orderedEnemies().size(), 256, "bounded copied-fact capacity");
        maximum.add(maximum.get(0));
        expectUnavailable(() -> evaluatePassedOuterGates(maximum));
        return 10;
    }
    private static void equal(Object actual, Object expected, String reason) {
        if (!java.util.Objects.equals(actual, expected)) throw new AssertionError(reason + "; actual=" + actual + "; expected=" + expected);
    }
    private static void expectUnavailable(Runnable action) {
        try { action.run(); } catch (IllegalArgumentException expected) { return; }
        throw new AssertionError("Missing/oversized supplied traversal facts accepted");
    }
}
